### PR TITLE
 Add Project.toml, switch to structs (immutable), update demos for Julia 1+

### PR DESCRIPTION
**Pull request by magerton**
- Adds Project.toml + Manifest.toml to be compatible w/ Julia 1.+
- Use `struct` instead of `mutable struct` for Basis, BasisMatrix, Interpoland, etc. This is because while the values in the underlying matrices can change, the matrices themselves probably shouldn't
- Update demos + example.ipynb to run with Julia 1+

### CODE REVIEW

**Comment by sglyon** [comment]
Thank you for working on this!

I will hopefully be able to review within the next week or two.

Thanks for understanding

**Comment by magerton** [comment]
Thanks, @sglyon! No rush -- I'm just getting my course materials all together to start teaching in mid Sept. I'll be using `BasisMatrices.jl` and want to make sure things are up-to-date for that. 😃

**Comment by sglyon** [comment]
Most of this looks great! I need to sort out CI again to get tests running.

In the meantime would you please delete the Manifest.toml in the root of this repository. I believe standard practice is to only commit that for "applications" and not libraries. With that rule of thumb, I think we can keep the demo/Manifest.toml intact

**Comment by magerton** [comment]
Thanks, @sglyon. Good to know re: `Manifest.toml`, which is now dropped.

**Comment by sglyon** [comment]
Thank you!

**Comment by magerton** [comment]
HTH!

**Pull request merged**
